# Pandas

#### Series Creation

In [2]:
!pip install pandas

Collecting pandas
  Using cached pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=1.26.0 in /home/akhil/Assingment/env/lib/python3.12/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/akhil/Assingment/env/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/akhil/Assingment/env/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
Installing collected packages: pandas
Successfully installed pandas-3.0.3

In [39]:
import pandas as pd
import numpy as np

In [40]:
df = pd.Series([1, 2, 3, 4, 5])
df

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [41]:
print(df.max())

5

In [42]:
print(df.mean())

3.0

Data Frame Creation

In [43]:
data = {
    "Name":["John", "Alice", "Bob", "Eve","Rakesh"],
    "Department": ["HR", "Finance", "IT", "Marketing","IT"],
    "Salary": [50000, 60000, 70000, 80000,90000],
    "Joining Date": ["2020-01-01", "2019-05-15", "2021-03-10", "2018-11-20","2022-07-01"]
}
df = pd.DataFrame(data)
df

     Name Department  Salary Joining Date
0    John         HR   50000   2020-01-01
1   Alice    Finance   60000   2019-05-15
2     Bob         IT   70000   2021-03-10
3     Eve  Marketing   80000   2018-11-20
4  Rakesh         IT   90000   2022-07-01

Data selection

In [47]:
df[df["Department"] == "IT"]

     Name Department  Salary Joining Date
2     Bob         IT   70000   2021-03-10
4  Rakesh         IT   90000   2022-07-01

In [48]:
df[df['Salary'] > 50000]

     Name Department  Salary Joining Date
1   Alice    Finance   60000   2019-05-15
2     Bob         IT   70000   2021-03-10
3     Eve  Marketing   80000   2018-11-20
4  Rakesh         IT   90000   2022-07-01

In [49]:
print(df[['Name', 'Salary']])

     Name  Salary
0    John   50000
1   Alice   60000
2     Bob   70000
3     Eve   80000
4  Rakesh   90000

Data Cleaning

In [50]:
data = {
    "Name":["John", "Alice", "Bob", "Eve","Rakesh"],
    "Departmnet": ["HR",None , "IT", "Marketing","IT"],
    "Salary": [50000, 60000, 70000, 80000,np.nan],
    "Joining Date": ["2020-01-01", "2019-05-15", "2021-03-10", "2018-11-20","2022-07-01"]
}
df_ = pd.DataFrame(data)
df_

     Name Departmnet   Salary Joining Date
0    John         HR  50000.0   2020-01-01
1   Alice        NaN  60000.0   2019-05-15
2     Bob         IT  70000.0   2021-03-10
3     Eve  Marketing  80000.0   2018-11-20
4  Rakesh         IT      NaN   2022-07-01

In [51]:
df_.isnull().sum()

Name            0
Departmnet      1
Salary          1
Joining Date    0
dtype: int64

In [52]:
df_["Salary"] =df_["Salary"].fillna(df_["Salary"].mean(), inplace=True)

/tmp/ipykernel_46188/807856032.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_["Salary"] =df_["Salary"].fillna(df_["Salary"].mean(), inplace=True)

In [53]:
df_

     Name Departmnet   Salary Joining Date
0    John         HR  50000.0   2020-01-01
1   Alice        NaN  60000.0   2019-05-15
2     Bob         IT  70000.0   2021-03-10
3     Eve  Marketing  80000.0   2018-11-20
4  Rakesh         IT  65000.0   2022-07-01

In [54]:
df_.dropna()

     Name Departmnet   Salary Joining Date
0    John         HR  50000.0   2020-01-01
2     Bob         IT  70000.0   2021-03-10
3     Eve  Marketing  80000.0   2018-11-20
4  Rakesh         IT  65000.0   2022-07-01

Grouping and Aggregation

In [55]:
df

     Name Department  Salary Joining Date
0    John         HR   50000   2020-01-01
1   Alice    Finance   60000   2019-05-15
2     Bob         IT   70000   2021-03-10
3     Eve  Marketing   80000   2018-11-20
4  Rakesh         IT   90000   2022-07-01

In [56]:
df.groupby("Department")["Salary"].mean()

Department
Finance      60000.0
HR           50000.0
IT           80000.0
Marketing    80000.0
Name: Salary, dtype: float64

In [58]:
df.groupby("Department")["Salary"].max()

Department
Finance      60000
HR           50000
IT           90000
Marketing    80000
Name: Salary, dtype: int64

In [64]:
df.groupby("Department")["Name"].count()

Department
Finance      1
HR           1
IT           2
Marketing    1
Name: Name, dtype: int64

Merging and Joining

In [65]:
data_ = {
    "Name":["John", "Alice", "Bob", "Eve","Rakesh"],
    "Project": ["A", "B", "A", "C","B"],
}
df2 = pd.DataFrame(data_)
df2

     Name Project
0    John       A
1   Alice       B
2     Bob       A
3     Eve       C
4  Rakesh       B

In [66]:
df.merge(df2, on="Name", how="inner")

     Name Department  Salary Joining Date Project
0    John         HR   50000   2020-01-01       A
1   Alice    Finance   60000   2019-05-15       B
2     Bob         IT   70000   2021-03-10       A
3     Eve  Marketing   80000   2018-11-20       C
4  Rakesh         IT   90000   2022-07-01       B

### Real world Data

In [67]:
!pip install seaborn

Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /home/akhil/Assingment/env/lib/python3.12/site-packages (from seaborn) (2.5.1)
Requirement already satisfied: pandas>=1.2 in /home/akhil/Assingment/env/lib/python3.12/site-packages (from seaborn) (3.0.3)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Using cached matplotlib-3.11.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached fonttools-4.63.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (118 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: packaging>=20.0 in /home/akhil/Assingment/env/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Collecting pillow>=9 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached pillow-12.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting pyparsing>=3 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in /home/akhil/Assingment/env/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/akhil/Assingment/env/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached matplotlib-3.11.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (10.0 MB)
Using cached contourpy-1.3.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (362 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.63.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.0 MB)
Using cached kiwisolver-1.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
Using cached pillow-12.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.63.0 kiwisolver-1.5.0 matplotlib-3.11.0 pillow-12.3.0 pyparsing-3.3.2 seaborn-0.13.2

In [68]:
import seaborn as sns

In [69]:
df = sns.load_dataset("tips")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [70]:
df.groupby("day")["tip"].mean()

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

In [72]:
df.groupby("sex")["total_bill"].sum()

sex
Male      3256.82
Female    1570.95
Name: total_bill, dtype: float64

In [76]:
df[["tip", "total_bill"]].corr()

                 tip  total_bill
tip         1.000000    0.675734
total_bill  0.675734    1.000000

### Bonus Chanllenge

In [92]:
def analyze(path):
    df = pd.read_csv(path)
    df["Revenue"] = df["Quantity"] * df["Price"]
    total_revenue = df.groupby("Product")["Revenue"].sum().sort_values(ascending=False)
    
    best_selling = df.groupby("Product")["Quantity"].sum().sort_values(ascending=False)[:3]
    
    return total_revenue,best_selling

In [93]:
total_revenue , best_selling = analyze("sales_data.csv")
print("Total Revenue by Products are :")
print(total_revenue)
print("Best 3 products are :")
print(best_selling)

Total Revenue by Products are :
Product
Laptop        202000
Monitor        51000
Printer        44000
SSD            40000
Headphones     26800
Webcam         26600
Router         21400
USB Drive      19250
Keyboard       13000
Mouse           8700
Name: Revenue, dtype: int64
Best 3 products are :
Product
USB Drive     25
Mouse         13
Headphones    10
Name: Quantity, dtype: int64